### PR TITLE
Avoid changing file contents if format failed

### LINKED ISSUE #273: When the file is not added to git, the contents are emptied on format
image

↑↑↑ Choose like the picture ↑↑↑

When you create a new proto file that hasn't been added to git yet.
When you run Goland's Format, it clears out all the content you've edited.

If the file is added to git, it works fine.

[Expect]
Don't delete what I'm trying to edit

### PR DESCRIPTION
**Pull request by pkwarren**
Update formatter to check the exit code of the command, and only reformat the file if it exits with a 0 exit code. If `buf format` returns an error, show up to 10 lines of stderr to help diagnose any issues.

Fixes #273.

### CODE REVIEW

File: src/main/kotlin/build/buf/intellij/formatter/BufFormatterService.kt [hunk 1]
```diff
@@ -58,14 +59,24 @@ class BufFormatterService : AsyncDocumentFormattingService() {
...
-                    request.onTextReady(output.joinToString(separator = ""))
+                    return
                 }
+                val stderrLimited = result.stderr.split(System.lineSeparator()).stream()
+                    .limit(10)
+                    .collect(Collectors.joining(System.lineSeparator()))
+                request.onError(
+                    BufBundle.message("formatter.title"),
+                    stderrLimited,
+                )
```
Comment (timostamm) [inline src/main/kotlin/build/buf/intellij/formatter/BufFormatterService.kt:79]: I'm a bit unsure whether a popup (I'm assuming this is how the error will show) is good DX here. I expect that the IDE will already report syntax errors, and this could have odd side-effects with "reformat code on save" enabled.

On the other hand, it's very possible that the IDE doesn't report all errors that prevent a successful `buf format`. Considering that the current DX with "reformat code on save" is currently much worse, I think it's a good call to add the popup.

**Review by timostamm — APPROVED** [review]

File: src/main/kotlin/build/buf/intellij/formatter/BufFormatterService.kt (hunk 1 above)
Comment (pkwarren) [reply src/main/kotlin/build/buf/intellij/formatter/BufFormatterService.kt:79]: I wasn't sure the level of reporting we want here. Any errors running `buf format` will be logged as a warning to idea.log.

This doesn't show as a modal popup but instead a notification at the bottom right (which auto hides after a delay).

Comment (pkwarren) [reply src/main/kotlin/build/buf/intellij/formatter/BufFormatterService.kt:79]: I did check a few other format implementations that shell out to external processes and they do report errors this way (with stderr).
