### PR TITLE
Fix linting in IntelliJ plugin

### LINKED ISSUE #321: Buf plugin does not seem to provide any linting, throws error
I don't see any sort of linting or buf suggestions going on. IDE says that an error is getting thrown from the Buf plugin. This is from Goland 2025.1 on Apple arm64.

Image

```
java.lang.IllegalArgumentException: Invalid offsets: start=357; end=376; document length=0
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:55)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:37)
	at com.intellij.openapi.editor.impl.DocumentImpl.createRangeMarker(DocumentImpl.java:541)
	at com.intellij.openapi.editor.Document.createRangeMarker(Document.java:225)
	at com.intellij.codeInsight.daemon.impl.HighlightInfo.lambda$getOrCreate$5(HighlightInfo.java:1207)
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.computeIfAbsent(Long2ObjectOpenHashMap.java:455)
	at com.intellij.codeInsight.daemon.impl.HighlightInfo.getOrCreate(HighlightInfo.java:1207)
	at com.intellij.codeInsight.daemon.impl.HighlightInfo.updateDescriptorFixRanges(HighlightInfo.java:1230)
	at com.intellij.codeInsight.daemon.impl.HighlightInfo.updateFields(HighlightInfo.java:1149)
	at com.intellij.codeInsight.daemon.impl.HighlightInfo.registerFixes(HighlightInfo.java:1114)
	at com.intellij.codeInsight.daemon.impl.HighlightInfo.fromAnnotation(HighlightInfo.java:767)
	at com.intellij.codeInsight.daemon.impl.HighlightInfo.fromAnnotation(HighlightInfo.java:740)
	at build.buf.intellij.annotator.BufAnalyzePass.getHighlights(BufAnalyzePass.kt:177)
	at build.buf.intellij.annotator.BufAnalyzePass.access$getHighlights(BufAnalyzePass.kt:63)
	at build.buf.intellij.annotator.BufAnalyzePass$doApplyInformationToEditor$update$1$run$1$1.invoke(BufAnalyzePass.kt:133)
	at build.buf.intellij.annotator.BufAnalyzePass$doApplyInformationToEditor$update$1$run$1$1.invoke(BufAnalyzePass.kt:129)
	at com.intellij.openapi.application.ActionsKt.runReadAction$lambda$3(actions.kt:25)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction$lambda$9(AnyThreadWriteThreadingSupport.kt:367)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction$lambda$10(AnyThreadWriteThreadingSupport.kt:455)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithTemporaryThreadLocal(AnyThreadWriteThreadingSupport.kt:204)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:455)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:367)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:944)
	at com.intellij.openapi.application.ActionsKt.runReadAction(actions.kt:25)
	at build.buf.intellij.annotator.BufAnalyzePass$doApplyInformationToEditor$update$1.run$lambda$0(BufAnalyzePass.kt:129)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$runUnderDisposeAwareIndicator$15(BackgroundTaskUtil.java:371)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:229)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:43)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:680)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:755)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:711)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:77)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:209)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:366)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:349)
	at build.buf.intellij.annotator.BufAnalyzePass$doApplyInformationToEditor$update$1.run(BufAnalyzePass.kt:125)
	at com.intellij.util.ui.update.Update.execute$suspendImpl(Update.kt:60)
	at com.intellij.util.ui.update.Update.execute(Update.kt)
	at com.intellij.util.ui.update.MergingUpdateQueue.executeUpdates$suspendImpl(MergingUpdateQueue.kt:364)
	at com.intellij.util.ui.update.MergingUpdateQueue.executeUpdates(MergingUpdateQueue.kt)
	at com.intellij.util.ui.update.MergingUpdateQueue$restart$1.invokeSuspend(MergingUpdateQueue.kt:344)
	at com.intellij.util.ui.update.MergingUpdateQueue$restart$1.invoke(MergingUpdateQueue.kt)
	at com.intellij.util.ui.update.MergingUpdateQueue$restart$1.invoke(MergingUpdateQueue.kt)
	at com.intellij.util.SingleAlarm$scheduleTask$1$1$1.invokeSuspend(SingleAlarm.kt:394)
	at com.intellij.util.SingleAlarm$scheduleTask$1$1$1.invoke(SingleAlarm.kt)
	at com.intellij.util.SingleAlarm$scheduleTask$1$1$1.invoke(SingleAlarm.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:155)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.util.SingleAlarm$scheduleTask$1$1.invokeSuspend(SingleAlarm.kt:392)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
```

### PR DESCRIPTION
**Pull request by pkwarren**
Starting in the 2025.1 release, long deprecated APIs relied on by the analysis pass are no longer functioning. Migrate off AnnotationImpl and AnnotationHolder to use HighlightInfo.

As part of this change, we're going to bump the minor version of the plugin and target 2025.1 as the min supported version. Also upgrade to the latest Gradle and IntelliJ gradle plugin.

Fixes #321.

### CODE REVIEW

File: gradle.properties [hunk 1]
```diff
@@ -4,25 +4,24 @@ pluginGroup = intellij
 pluginName = intellij-buf
 pluginRepositoryUrl = https://github.com/bufbuild/intellij-buf
 # SemVer format -> https://semver.org
-pluginVersion = 0.5.1
+pluginVersion = 0.6.0
 
 # Supported build number ranges and IntelliJ Platform versions -> https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html
-pluginSinceBuild = 242
+pluginSinceBuild = 251
```
Comment (pkwarren) [inline gradle.properties:10]: Since the breakage occurred in this version, targeting that as the min version for the next release of the plugin.

File: gradle.properties [hunk 2]
```diff
@@ -4,25 +4,24 @@ pluginGroup = intellij
...
 platformType = IU
-platformVersion = 2024.2
+platformVersion = 2025.1
 
 # Plugin Dependencies -> https://plugins.jetbrains.com/docs/intellij/plugin-dependencies.html
 # Example: platformPlugins = com.intellij.java, com.jetbrains.php:203.4449.22
 platformPlugins = io.kanro.idea.plugin.protobuf:2.0.2
 # Example: platformBundledPlugins = com.intellij.java
-platformBundledPlugins = idea.plugin.protoeditor, org.jetbrains.plugins.yaml
+platformBundledPlugins = idea.plugin.protoeditor, org.jetbrains.plugins.yaml, com.intellij.modules.json
```
Comment (pkwarren) [inline gradle.properties:21]: Workaround for https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1930 which we've encountered in upgrading from 2.3.0 -> 2.5.0 of the plugin.

File: src/main/kotlin/build/buf/intellij/annotator/BufAnalyzePass.kt [hunk 3]
```diff
@@ -273,14 +262,16 @@ fun AnnotationHolder.createAnnotationsForFile(
...
+            .severity(severity)
+            .descriptionAndTooltip(issue.message)
             // TODO: Should handle file-level lint warnings here: https://github.com/bufbuild/intellij-buf/issues/215
             .range(issue.toTextRange(doc) ?: continue)
             .problemGroup { issue.type }
             .needsUpdateOnTyping(true)
-            .withFix(IgnoreBufIssueQuickFix(issue.type))
-
-        annotationBuilder.create()
+            .registerFix(IgnoreBufIssueQuickFix(issue.type), null, null, null, null)
```
Comment (pkwarren) [inline src/main/kotlin/build/buf/intellij/annotator/BufAnalyzePass.kt:273]: Didn't look in detail at the optional arguments here - verified that both linting and quick fixes work as they did before.

**Review by jhump — APPROVED** [review]
